# Attestation server configuration

[log]
format = "json"   # json, text
level  = "info"   # debug, info, warn, error

[server]
host = "0.0.0.0"
port = 8187

[paths]
build_info   = "/etc/build-info.json"
endorsements = "/etc/endorsements.json"

[report.evidence]
nitronsm    = false  # at least one must be true; nitronsm excludes all others
nitrotpm    = false
sevsnp      = false
sevsnp_vmpl = 0

[report.user_data]
env = []  # optional; environment variable names to include

[tls.public]
cert_path = ""
key_path  = ""

[tls.private]
cert_path = ""
key_path  = ""
