name: CI

on:
  push:
    branches-ignore: [main]
    paths-ignore:
      - "*.md"
      - "**/*.md"
      - LICENSE
      - NOTICE

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Check Formatting
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "Files not formatted:"
            echo "$unformatted"
            exit 1
          fi

      - name: Test
        env:
          DNSSEC_LIVE_TEST: "1"
        run: go test ./...

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./...
